=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/main/resources/sample/change.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://polaris.pivoto.cn/schema/change" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="changes" type="chan:changesType" xmlns:chan="http://polaris.pivoto.cn/schema/change"/>
	<xs:complexType name="changesType">
		<xs:annotation>
			<xs:documentation>转换配置组</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="baseChangeType">
				<xs:sequence>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element type="chan:packageType" name="package" maxOccurs="unbounded" minOccurs="1"
						xmlns:chan="http://polaris.pivoto.cn/schema/change"/>
					<xs:element type="chan:changeType" name="change" maxOccurs="unbounded" minOccurs="0"
						xmlns:chan="http://polaris.pivoto.cn/schema/change"/>
					</xs:choice>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="baseChangeType" abstract="true">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element type="xs:string" name="charset" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>文件编码</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:boolean" name="copy-all" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>是否复制未映射的文件。默认true</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:boolean" name="include-filename" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>是否同时处理符合映射关系的文件名。默认true</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="extensions" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>需要处理文件的扩展名，以逗号分隔，extensions与name-pattern匹配一个即认为匹配</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="name-pattern" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>需要处理文件名模式，extensions与name-pattern匹配一个即认为匹配</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="source-path" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>源代码相对路径</xs:documentation>
				</xs:annotation>
			</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="changeType">
		<xs:annotation>
			<xs:documentation>转换配置</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="baseChangeType">
				<xs:sequence>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element type="xs:string" name="src" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>来源根目录</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="xs:string" name="dest" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>目标根目录</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="chan:packageType" name="package" maxOccurs="unbounded" minOccurs="0"
						xmlns:chan="http://polaris.pivoto.cn/schema/change"/>
					</xs:choice>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="packageType">
		<xs:annotation>
			<xs:documentation>映射配置，多个配置会按顺序转换</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="required">
					<xs:annotation>
						<xs:documentation>源名称</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="mapping" use="required">
					<xs:annotation>
						<xs:documentation>映射名称</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== pivoto/polaris-toolkit/polaris-builder/polaris-builder-assembly/src/assembly/conf/change/change-polaris.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >
	<charset>utf-8</charset>
	<copy-all>true</copy-all>
	<include-filename>true</include-filename>
	<extensions>xml,java,properties,yml,json,vm,factories</extensions>
	<name-pattern>META-INF/services/.*</name-pattern>
	<name-pattern>META-INF/dubbo/.*</name-pattern>
	<source-path>main/java</source-path>
	<source-path>main/resources</source-path>
	<source-path>test/java</source-path>
	<source-path>test/resources</source-path>
	<!--<package name="io.polaris.framework.dubbo" mapping="com.jcfc.bf.trade"/>-->
	<package name="io.polaris.framework" mapping="com.jcfc.bf"/>
	<!--<package name="io.polaris.core" mapping="io.polaris.core"/>
	<package name="io.polaris" mapping="com.jcfc"/>-->

	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-starters/mybatix-spring-boot-starter/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-starters/mybatix-spring-boot-starter/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-starters/config-spring-cloud-starter/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-starters/config-spring-boot-starter/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-starters/basic-framework-spring-boot-starter/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-starters/basic-framework-spring-boot-starter/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-starters/toolkit-spring-boot-starter/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-starters/toolkit-spring-boot-starter/src</dest>
	</change>

	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-core/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-core/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-dubbo/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-dubbo/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-http/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-http/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-infra/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-infra/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-mq/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-mq/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-nacos/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-nacos/src</dest>
	</change>
	<change>
		<src>O:/me/@@/awesome-code/dev/polaris-framework/polaris-framework-modules/polaris-framework-module-redis/src</src>
		<dest>O:/jcfc/plat/jcfc-framework/jcfc-framework-modules/jcfc-framework-module-redis/src</dest>
	</change>

</changes>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/assembly/conf/change/change.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >
	<charset>utf-8</charset>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-commons/stdk-core/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-core/src</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>
		<name-pattern>META-INF/services/.*</name-pattern>
		<source-path>main/java</source-path>
		<source-path>main/resources</source-path>
		<source-path>test/java</source-path>
		<source-path>test/resources</source-path>
		<package name="com.jcfc.stdk.commons" mapping="io.polaris.core"/>
		<package name="com.jcfc.stdk" mapping="io.polaris"/>
		<package name="com.jcfc" mapping="io.polaris"/>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-extra-validator/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-extra/polaris-extra-validator/src</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>
		<name-pattern>META-INF/services/.*</name-pattern>
		<source-path>main/java</source-path>
		<source-path>main/resources</source-path>
		<source-path>test/java</source-path>
		<source-path>test/resources</source-path>
		<package name="com.jcfc.stdk" mapping="io.polaris"/>
		<package name="com.jcfc" mapping="io.polaris"/>
	</change>

	<!-- region polaris-annotation-processor -->
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-commons/stdk-annotation-processor/stdk-annotation-processor-core/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-core/src</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>
		<name-pattern>META-INF/services/.*</name-pattern>
		<source-path>main/java</source-path>
		<source-path>main/resources</source-path>
		<source-path>test/java</source-path>
		<source-path>test/resources</source-path>
		<package name="com.jcfc.stdk.commons" mapping="io.polaris"/>
		<package name="com.jcfc.stdk" mapping="io.polaris"/>
		<package name="com.jcfc" mapping="io.polaris"/>
		<package name="stdk-annotation-processor" mapping="polaris-annotation-processor"/>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-commons/stdk-annotation-processor/stdk-annotation-processor-service/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-service/src</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>
		<name-pattern>META-INF/services/.*</name-pattern>
		<source-path>main/java</source-path>
		<source-path>main/resources</source-path>
		<source-path>test/java</source-path>
		<source-path>test/resources</source-path>
		<package name="com.jcfc.stdk.commons" mapping="io.polaris"/>
		<package name="com.jcfc.stdk" mapping="io.polaris"/>
		<package name="com.jcfc" mapping="io.polaris"/>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-commons/stdk-annotation-processor/stdk-annotation-processor-test/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-test/src</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>
		<name-pattern>META-INF/services/.*</name-pattern>
		<source-path>main/java</source-path>
		<source-path>main/resources</source-path>
		<source-path>test/java</source-path>
		<source-path>test/resources</source-path>
		<package name="com.jcfc.stdk.commons" mapping="io.polaris"/>
		<package name="com.jcfc.stdk" mapping="io.polaris"/>
		<package name="com.jcfc" mapping="io.polaris"/>
	</change>
	<!-- endregion polaris-annotation-processor -->

</changes>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/main/resources/sample/sample.change.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >

	<!--文件编码-->
	<charset>utf-8</charset>
	<!--是否复制未映射的文件。默认true-->
	<copy-all>true</copy-all>
	<!--是否同时处理符合映射关系的文件名。默认true-->
	<include-filename>true</include-filename>
	<!--需要处理文件的扩展名，以逗号分隔-->
	<extensions>xml,java,properties,yml,json</extensions>
	<!--源代码相对路径-->
	<source-path>java</source-path>
	<source-path>resources</source-path>
	<!--映射配置，多个配置会按顺序转换-->
	<package name="io.polaris" mapping="cn.pivoto.polaris"/>
	<package name="io.gitee" mapping="io.github"/>


	<change>
		<!--来源根目录-->
		<src>./src/main</src>
		<!--目标根目录-->
		<dest>./target/src/main</dest>
	</change>
	<change>
		<!-- charset-->
		<charset>utf-8</charset>
		<src>./src/main</src>
		<dest>./target/src/main</dest>
		<copy-all>true</copy-all>
		<include-filename>true</include-filename>
		<extensions>xml,java,properties,yml,json</extensions>

		<source-path>java</source-path>
		<source-path>resources</source-path>

		<package name="io.polaris" mapping="cn.pivoto.polaris"/>
		<package name="io.gitee" mapping="io.github"/>
	</change>

</changes>

=== pivoto/polaris-toolkit/polaris-projects/polaris-builder/src/assembly/conf/change/change-reverse.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >
	<charset>utf-8</charset>
	<copy-all>true</copy-all>
	<include-filename>true</include-filename>
	<extensions>xml,java,properties,yml,json,vm</extensions>
	<name-pattern>META-INF/services/.*</name-pattern>
	<source-path>main/java</source-path>
	<source-path>main/resources</source-path>
	<source-path>test/java</source-path>
	<source-path>test/resources</source-path>
	<package name="io.polaris.annotation.processing" mapping="com.jcfc.stdk.annotation.processing"/>
	<package name="io.polaris.core" mapping="com.jcfc.stdk.core"/>
	<package name="io.polaris" mapping="com.jcfc.stdk"/>
	<package name="polaris-annotation-processor" mapping="stdk-annotation-processor"/>
	<package name="polaris-core-annotation-processor" mapping="stdk-core-annotation-processor"/>
	<!--<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-builder/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-builder/src</dest>
	</change>-->
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-plugins/polaris-build-tools/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-build-tools/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-core/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-core/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-core-annotation-processor/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-core-annotation-processor/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-validator/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-validator/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-bytecode/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-bytecode/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-web/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-web/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-image/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-image/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-crypto/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-crypto/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-mybatis/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-mybatis/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-demo/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-demo/src</dest>
	</change>

</changes>

=== pivoto/polaris-toolkit/polaris-projects/polaris-builder/src/assembly/conf/change/change.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >
	<charset>utf-8</charset>
	<copy-all>true</copy-all>
	<include-filename>true</include-filename>
	<extensions>xml,java,properties,yml,json,vm</extensions>
	<name-pattern>META-INF/services/.*</name-pattern>
	<source-path>main/java</source-path>
	<source-path>main/resources</source-path>
	<source-path>test/java</source-path>
	<source-path>test/resources</source-path>
	<package name="com.jcfc.stdk.annotation.processing" mapping="io.polaris.annotation.processing"/>
	<package name="com.jcfc.stdk.core" mapping="io.polaris.core"/>
	<package name="com.jcfc.stdk" mapping="io.polaris"/>
	<package name="com.jcfc" mapping="io.polaris"/>
	<package name="stdk-annotation-processor" mapping="polaris-annotation-processor"/>
	<package name="stdk-core-annotation-processor" mapping="polaris-core-annotation-processor"/>

	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-build-tools/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-plugins/polaris-build-tools/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-builder/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-builder/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-core/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-core/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-core-annotation-processor/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-core-annotation-processor/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-validator/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-validator/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-bytecode/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-bytecode/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-web/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-web/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-image/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-image/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-crypto/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-crypto/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-mybatis/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-extra/polaris-mybatis/src</dest>
	</change>
	<change>
		<src>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-demo/src</src>
		<dest>D:/xcode/me/@@/awesome/code/dev/polaris-toolkit/polaris-projects/polaris-demo/src</dest>
	</change>

</changes>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/assembly/conf/change/change-reverse.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/change" xsi:schemaLocation="http://polaris.pivoto.cn/schema/change change.xsd" >
	<charset>utf-8</charset>
	<copy-all>true</copy-all>
	<include-filename>true</include-filename>
	<extensions>xml,java,properties,yml,json</extensions>
	<name-pattern>META-INF/services/.*</name-pattern>
	<source-path>main/java</source-path>
	<source-path>main/resources</source-path>
	<source-path>test/java</source-path>
	<source-path>test/resources</source-path>
	<package name="io.polaris.annotation.processing" mapping="com.jcfc.stdk.annotation.processing"/>
	<package name="io.polaris.core" mapping="com.jcfc.stdk.core"/>
	<package name="io.polaris" mapping="com.jcfc.stdk"/>
	<package name="polaris-annotation-processor" mapping="stdk-annotation-processor"/>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-core/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-core/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-extra/polaris-extra-validator/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-extra-validator/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-extra/polaris-extra-bytecode/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-extra-bytecode/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-extra/polaris-extra-log/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-extra/stdk-extra-log/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-core/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-annotation-processor/stdk-annotation-processor-core/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-service/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-annotation-processor/stdk-annotation-processor-service/src</dest>
	</change>
	<change>
		<src>D:/xcode/me/@@/awesome/code/dev/coding/polaris/polaris-toolkit/polaris-annotation-processor/polaris-annotation-processor-test/src</src>
		<dest>D:/xcode/jcfc/plat/base/jcfc-stdk/stdk-annotation-processor/stdk-annotation-processor-test/src</dest>
	</change>

</changes>
