=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/main/resources/sample/code.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://polaris.pivoto.cn/schema/code">
	<xs:element name="code" type="codeType"/>

	<xs:complexType name="prefixOrSuffix" abstract="true">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element type="xs:string" name="table-prefix" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>需忽略的表名前缀，多个间逗号分隔</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element type="xs:string" name="table-suffix" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>需忽略的表名后缀，多个间逗号分隔</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element type="xs:string" name="column-prefix" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>需忽略的列名前缀，多个间逗号分隔</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element type="xs:string" name="column-suffix" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>需忽略的列名后缀，多个间逗号分隔</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element type="mappingsType" name="mappings" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>配置jdbc类型与java类型的映射关系，覆盖默认值</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnsType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element type="columnType" name="column" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>配置表字段的自定义java类型等，覆盖默认值</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="required">
					<xs:annotation>
						<xs:documentation>name，列名称</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="javaType" use="required">
					<xs:annotation>
						<xs:documentation>javaType，如java.lang.String</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="mappingsType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element type="mappingType" name="mapping" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>配置jdbc类型与java类型的映射关系，覆盖默认值</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mappingType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="jdbcType" use="required">
					<xs:annotation>
						<xs:documentation>jdbcType，参见java.sql.Types字段，如VARCHAR</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="javaType" use="required">
					<xs:annotation>
						<xs:documentation>javaType，如java.lang.String</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="codeType">
		<xs:complexContent>
			<xs:extension base="prefixOrSuffix">
				<xs:sequence>
					<xs:element type="xs:string" name="outdir" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>配置生成代码的位置</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="propertyType" name="property" maxOccurs="1" minOccurs="0">
						<xs:annotation>
							<xs:documentation>全局扩展属性配置</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="groupsType" name="groups" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>可配置多个组以使用不同的配置</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="entryType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="key" use="required">
					<xs:annotation>
						<xs:documentation>属性名</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="value" use="optional">
					<xs:annotation>
						<xs:documentation>属性值</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:sequence>
			<xs:element type="entryType" name="entry" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>扩展属性配置</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="groupsType">
		<xs:sequence>
			<xs:element type="groupType" name="group" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>代码生成配置组</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="groupType">
		<xs:complexContent>
			<xs:extension base="prefixOrSuffix">
				<xs:sequence>
					<xs:element type="propertyType" name="property" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>扩展属性配置</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="templatesType" name="templates" minOccurs="0">
						<xs:annotation>
							<xs:documentation>模板配置</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="tablesType" name="tables" minOccurs="0">
						<xs:annotation>
							<xs:documentation>
								tables: 配置待生成代码的表<br/>
								table.catalog: 数据库名，按需配置。如oracle下不需要, mysql下需要<br/>
								table.schema: 数据库用户, 大小写敏感。如oracle下需要大写<br/>
								table.name: 表名, 大小写敏感。如oracle下需要大写<br/>
								table.package: 目标代码的包名, 如io.polaris.module.submodule<br/>
								table.property: 扩展属性<br/>
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="templatesType">
		<xs:sequence>
			<xs:element type="templateType" name="template" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>模板配置</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="templateType">
		<xs:sequence>
			<xs:element name="path" type="xs:string">
				<xs:annotation>
					<xs:documentation>模板路径</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dirname" type="xs:string">
				<xs:annotation>
					<xs:documentation>输出的相对路径</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="filename" type="xs:string">
				<xs:annotation>
					<xs:documentation>输出文件名</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="propertyType" name="property" maxOccurs="1" minOccurs="0">
				<xs:annotation>
					<xs:documentation>扩展属性配置</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tablesType">
		<xs:sequence>
			<xs:element type="tableType" name="table" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tableType">
		<xs:complexContent>
			<xs:extension base="prefixOrSuffix">
				<xs:sequence>
					<xs:element type="propertyType" name="property" maxOccurs="1" minOccurs="0">
						<xs:annotation>
							<xs:documentation>扩展属性配置</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element type="columnsType" name="columns" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>配置表字段的自定义java类型等，覆盖默认值</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
				<xs:attribute type="xs:string" name="catalog" use="optional">
					<xs:annotation>
						<xs:documentation>数据库名，按需配置。如：oracle下不需要, mysql下需要</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="schema" use="optional">
					<xs:annotation>
						<xs:documentation>数据库用户, 大小写敏感。如oracle下需要大写</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="name" use="required">
					<xs:annotation>
						<xs:documentation>表名, 大小写敏感。如oracle下需要大写</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="package" use="required">
					<xs:annotation>
						<xs:documentation>目标代码的包名, 如io.polaris.module.submodule</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/main/resources/sample/sample.code.xml
<?xml version="1.0" encoding="UTF-8"?>
<code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/code" xsi:schemaLocation="http://polaris.pivoto.cn/schema/code code.xsd" >
	<!--
	属性优先级: 表属性 > 模板属性 > 组属性 > 全局属性
	-->
	<!-- outdir: 配置生成代码的位置 -->
	<outdir>./target/code</outdir>
	<!-- 需忽略的表名前缀，多个间逗号分隔 -->
	<table-prefix>_,t_,tbl_</table-prefix>
	<!-- 需忽略的表名后缀，多个间逗号分隔 -->
	<table-suffix>_,_bak,_tmp</table-suffix>
	<!-- 需忽略的列名前缀，多个间逗号分隔 -->
	<column-prefix>_</column-prefix>
	<!-- 需忽略的列名后缀，多个间逗号分隔 -->
	<column-suffix>_</column-suffix>
	<mappings>
		<mapping jdbcType="VARCHAR" javaType="java.lang.String" />
	</mappings>
	<!-- 扩展属性配置 -->
	<property>
		<!-- 扩展属性配置 -->
		<entry key="author" value="Qt"/>
		<entry key="useGeneratedKeys" value="true"/>
		<entry key="srcDir" value="src/main/java"/>
		<entry key="webDir" value="src/main/resources/META-INF/resources"/>
		<entry key="entityPackage" value="entity"/>
		<entry key="mapperPackage" value="mapper"/>
		<entry key="servicePackage" value="service"/>
		<entry key="implPackage" value="impl"/>
		<entry key="controllerPackage" value="controller"/>
	</property>

	<!-- 可配置多个组以使用不同的配置 -->
	<groups>
		<!-- 代码生成配置组 -->
		<group>
			<!-- 扩展属性配置 -->
			<property></property>
			<!-- 模板配置 -->
			<templates>
				<!-- 模板配置 -->
				<template>
					<!-- 扩展属性配置 -->
					<property></property>
					<!-- 模板路径 -->
					<path>/vm/example.txt.vm</path>
					<!-- 输出的相对路径 -->
					<dirname>//</dirname>
					<!-- 输出文件名 -->
					<filename>${table.javaClassName}.example.txt</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/base/entity/Entity.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.entityPackage}</dirname>
					<filename>${table.javaClassName}Entity.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/base/mapper/Mapper.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</dirname>
					<filename>${table.javaClassName}Mapper.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/resources/Mapper.xml.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</dirname>
					<filename>${table.javaClassName}Mapper.xml</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/base/service/Service.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}</dirname>
					<filename>${table.javaClassName}Service.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/base/service/IService.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}</dirname>
					<filename>I${table.javaClassName}Service.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/base/service/ServiceImpl.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}/${env.implPackage}</dirname>
					<filename>${table.javaClassName}ServiceImpl.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/facade/controller/Controller.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.controllerPackage}</dirname>
					<filename>${table.javaClassName}Controller.java</filename>
				</template>
			</templates>
			<tables>
				<table catalog="" schema="BASESV" name="ARM_BCH" package="io.polaris.app">
					<property></property>
				</table>
				<table catalog="" schema="BASESV" name="ARM_USER" package="io.polaris.app">
					<property></property>
				</table>
			</tables>

		</group>
		<group>
			<property></property>
		</group>
	</groups>
</code>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/assembly/conf/code/sample.code.xml
<?xml version="1.0" encoding="UTF-8"?>
<code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/code" xsi:schemaLocation="http://polaris.pivoto.cn/schema/code code.xsd" >
	<!--
	属性优先级: 表属性 > 模板属性 > 组属性 > 全局属性
	-->
	<!-- outdir: 配置生成代码的位置 -->
	<outdir>./</outdir>
	<!-- region 全局属性配置 -->
	<property>
		<entry key="author" value="Qt"/>
		<entry key="useGeneratedKeys" value="true"/>
		<entry key="srcDir" value="src/main/java"/>
		<entry key="webDir" value="src/main/resources/META-INF/resources"/>
		<entry key="entityPackage" value="entity"/>
		<entry key="mapperPackage" value="mapper"/>
		<entry key="servicePackage" value="service"/>
		<entry key="implPackage" value="impl"/>
		<entry key="controllerPackage" value="controller"/>
	</property>
	<!-- endregion 全局属性配置 -->

	<!-- 可配置多个组以使用不同的配置 -->
	<groups>
		<!-- region 代码生成配置组 -->
		<group>
			<!-- 组扩展属性配置-->
			<property></property>
			<templates>
				<template>
					<property></property>
					<path>/vm/example.txt.vm</path>
					<outdir>${env.srcDir}/</outdir>
					<filename>${table.javaClassName}.example.txt</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/entity.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.entityPackage}</outdir>
					<filename>${table.javaClassName}Entity.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/mapper.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</outdir>
					<filename>${table.javaClassName}Mapper.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/mapper.xml.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</outdir>
					<filename>${table.javaClassName}Mapper.xml</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/service.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}</outdir>
					<filename>I${table.javaClassName}Service.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/service-impl.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}/${env.implPackage}</outdir>
					<filename>${table.javaClassName}ServiceImpl.java</filename>
				</template>
			</templates>

			<!--
				tables: 配置待生成代码的表
				table.catalog: 数据库名, oracle下不需要, mysql下使用
				table.schema: 数据库用户, 大小写敏感, oracle下需要大写
				table.name: 表名, 大小写敏感, oracle下需要大写
				table.package: java包名, 如 com.yucheng.cmis.模块名.子模块名
				table.property.moduleDir: 模块目录路径, sql文件、jsp文件等的目录名
				table.property.moduleId: 模块Java服务接口声明的模块ID, 通常与包名类似, 如 com.yucheng.cmis.模块名.子模块名
				table.property.moduleName: 模块Java服务接口声明的模块名称
			 -->
			<tables>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app">
					<property></property>
				</table>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app">
					<property></property>
				</table>
			</tables>

		</group>
		<group>
			<property></property>
		</group>
		<!-- endregion 代码生成配置组 -->
	</groups>
</code>

=== pivoto/polaris-toolkit/polaris/polaris-toolkit/polaris-builder/src/assembly/conf/code/code.xml
<?xml version="1.0" encoding="UTF-8"?>
<code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/code" xsi:schemaLocation="http://polaris.pivoto.cn/schema/code code.xsd" >
	<outdir>/tmp/code/</outdir>
	<property>
		<entry key="author" value="Qt"/>
		<entry key="useGeneratedKeys" value="true"/>
		<entry key="srcDir" value="src/main/java"/>
		<entry key="webDir" value="src/main/resources/META-INF/resources"/>
		<entry key="entityPackage" value="entity"/>
		<entry key="mapperPackage" value="mapper"/>
		<entry key="servicePackage" value="service"/>
		<entry key="implPackage" value="impl"/>
		<entry key="controllerPackage" value="controller"/>
	</property>

	<groups>
		<group>
			<property></property>
			<templates>
				<template>
					<property></property>
					<path>/vm/example.txt.vm</path>
					<outdir>/</outdir>
					<filename>${table.javaClassName}.example.txt</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/Entity.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.entityPackage}</outdir>
					<filename>${table.javaClassName}Entity.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/Mapper.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</outdir>
					<filename>${table.javaClassName}Mapper.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/resources/Mapper.xml.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</outdir>
					<filename>${table.javaClassName}Mapper.xml</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/Service.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}</outdir>
					<filename>${table.javaClassName}Service.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/java/Controller.java.vm</path>
					<outdir>${env.srcDir}/${table.javaPackageDir}/${env.controllerPackage}</outdir>
					<filename>${table.javaClassName}Controller.java</filename>
				</template>
			</templates>

			<tables>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app" >
					<property></property>
				</table>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app" >
					<property></property>
				</table>
			</tables>
		</group>
		<group>
			<property></property>
		</group>
	</groups>
</code>

=== pivoto/polaris-toolkit/polaris-projects/polaris-builder/src/assembly/conf/code/sample.code.xml
<?xml version="1.0" encoding="UTF-8"?>
<code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://polaris.pivoto.cn/schema/code" xsi:schemaLocation="http://polaris.pivoto.cn/schema/code code.xsd" >
	<!--
	属性优先级: 表属性 > 模板属性 > 组属性 > 全局属性
	-->
	<!-- outdir: 配置生成代码的位置 -->
	<outdir>./</outdir>
	<!-- 需忽略的表名前缀，多个间逗号分隔 -->
	<table-prefix>_,t_,tbl_</table-prefix>
	<!-- 需忽略的表名后缀，多个间逗号分隔 -->
	<table-suffix>_,_bak,_tmp</table-suffix>
	<!-- 需忽略的列名前缀，多个间逗号分隔 -->
	<column-prefix>_</column-prefix>
	<!-- 需忽略的列名后缀，多个间逗号分隔 -->
	<column-suffix>_</column-suffix>
	<!-- region 全局属性配置 -->
	<property>
		<entry key="author" value="Qt"/>
		<entry key="useGeneratedKeys" value="true"/>
		<entry key="srcDir" value="src/main/java"/>
		<entry key="webDir" value="src/main/resources/META-INF/resources"/>
		<entry key="entityPackage" value="entity"/>
		<entry key="mapperPackage" value="mapper"/>
		<entry key="servicePackage" value="service"/>
		<entry key="implPackage" value="impl"/>
		<entry key="controllerPackage" value="controller"/>
	</property>
	<!-- endregion 全局属性配置 -->

	<!-- 可配置多个组以使用不同的配置 -->
	<groups>
		<!-- region 代码生成配置组 -->
		<group>
			<!-- 组扩展属性配置-->
			<property></property>
			<templates>
				<template>
					<property></property>
					<path>/vm/example.txt.vm</path>
					<dirname>${env.srcDir}/</dirname>
					<filename>${table.javaClassName}.example.txt</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/entity.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.entityPackage}</dirname>
					<filename>${table.javaClassName}Entity.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/mapper.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</dirname>
					<filename>${table.javaClassName}Mapper.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/mapper.xml.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.mapperPackage}</dirname>
					<filename>${table.javaClassName}Mapper.xml</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/service.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}</dirname>
					<filename>I${table.javaClassName}Service.java</filename>
				</template>
				<template>
					<property></property>
					<path>/vm/service-impl.java.vm</path>
					<dirname>${env.srcDir}/${table.javaPackageDir}/${env.servicePackage}/${env.implPackage}</dirname>
					<filename>${table.javaClassName}ServiceImpl.java</filename>
				</template>
			</templates>

			<!--
				tables: 配置待生成代码的表
				table.catalog: 数据库名, oracle下不需要, mysql下使用
				table.schema: 数据库用户, 大小写敏感, oracle下需要大写
				table.name: 表名, 大小写敏感, oracle下需要大写
				table.package: java包名, 如 com.yucheng.cmis.模块名.子模块名
				table.property.moduleDir: 模块目录路径, sql文件、jsp文件等的目录名
				table.property.moduleId: 模块Java服务接口声明的模块ID, 通常与包名类似, 如 com.yucheng.cmis.模块名.子模块名
				table.property.moduleName: 模块Java服务接口声明的模块名称
			 -->
			<tables>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app">
					<property></property>
				</table>
				<table catalog="" schema="BASESV" name="BS_USER" package="io.polaris.app">
					<property></property>
				</table>
			</tables>

		</group>
		<group>
			<property></property>
		</group>
		<!-- endregion 代码生成配置组 -->
	</groups>
</code>
